<?php

namespace Masterpass\MerchantSDK\Impl;

/**
 * Header required for SDK tracking information.
 * @package  masterpass-merchant
 * @subpackage impl
 */
class APITrackerImpl implements IApiTracker{

    /* @const client sdk version generated by swagger */
	 const CLIENT_SDK_VERSION = "client_sdk_version=1.0.0";

	/* @const language version */
	 const LANG_VERSION = "lang_version=";

	/* @const language name*/
	 const PROGRAMMING_LANG = "lang_name=";

	/* @const language */
	 const PHP = "PHP";

	const COMMA = ",";

	 /* @const user agent to be passed in header */
	 const USER_AGENT_HEADER = "MC Open API OAuth Framework v1.0-PHP";

	 /* @const Plugin Version */
     const KEY_PLUGIN_VERSION = "plugin_version";

	 const EQUAL = "=";

    /**
	 * Returns client tracking string.
	 * @return String the client tracking string.
	 */
	public function getAPITrackingHeader(){
		$trackingHeader = '';
		$trackingHeader .= APITrackerImpl::CLIENT_SDK_VERSION.APITrackerImpl::COMMA;
		$trackingHeader .= APITrackerImpl::PROGRAMMING_LANG.APITrackerImpl::PHP.APITrackerImpl::COMMA;
		$trackingHeader .= APITrackerImpl::LANG_VERSION.phpversion();

		 if (!empty(MasterCardApiConfig::$additionalProperties)
				&& array_key_exists(APITrackerImpl::KEY_PLUGIN_VERSION,MasterCardApiConfig::$additionalProperties)) {
			$trackingHeader .= APITrackerImpl::COMMA.APITrackerImpl::KEY_PLUGIN_VERSION.APITrackerImpl::EQUAL.MasterCardApiConfig::$additionalProperties[APITrackerImpl::KEY_PLUGIN_VERSION];
		}

		return (string)$trackingHeader;
	}

	/**
	 * Returns user agent header value.
	 * @return the user agent header value.
	 */
	public function getUserAgentHeader() {
		return APITrackerImpl::USER_AGENT_HEADER;
	}

}
