<?php

namespace Masterpass\MerchantSDK\Models;

/**
 * DSRP
 *
 * PHP version 5
 *
 * @category Class
 * @package  masterpass-merchant
 */

/**
 * DSRP : This class contains methods require to set DSRP details during DSRP checkout.
 *
 * @category    Class
 * @description This class contains methods require to set DSRP details during DSRP checkout.
 * @package     masterpass-merchant
 * @subpackage  model
 */

class DSRP
{
    /**
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[]
      */
    static $attributeMap = array(
        'DSRPData' => 'DSRPData',
        'DSRPDataType' => 'DSRPDataType',
        'UnpredictableNumber' => 'UnpredictableNumber',
        'ExtensionPoint' => 'ExtensionPoint'
    );

    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'dsrp_data' => 'setDsrpData',
        'dsrp_data_type' => 'setDsrpDataType',
        'unpredictable_number' => 'setUnpredictableNumber',
        'extension_point' => 'setExtensionPoint'
    );

    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'dsrp_data' => 'getDsrpData',
        'dsrp_data_type' => 'getDsrpDataType',
        'unpredictable_number' => 'getUnpredictableNumber',
        'extension_point' => 'getExtensionPoint'
    );

    static function getters() {
        return self::$getters;
    }


    /**
      * $dsrp_data the DSRP cryptogram generated by the consumers MasterPass wallet.
      * @var string
      */
    public $DSRPData;

    /**
      * $dsrp_data_type the type of cryptogram generated by the consumers MasterPass wallet. MasterPass passes the most secure selection (ICC) if the merchant or service provider has indicated they can accept both types (UCAF, ICC).
      * @var string
      */
    public $DSRPDataType;

    /**
      * $unpredictable_number the encoded EMV-quality random number generated by either the merchant or MasterPass.
      * @var string
      */
    public $UnpredictableNumber;

    /**
      * $extension_point the ExtensionPoint for future enhancement.
      * @var \mastercard_masterpass_merchant\model\ExtensionPoint
      */
    public $ExtensionPoint;


    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {

        if ($data != null) {
            $this->DSRPData = isset($data["DSRPData"])?$data["DSRPData"]:"";
            $this->DSRPDataType = isset($data["DSRPDataType"])?$data["DSRPDataType"]:"";
            $this->UnpredictableNumber = isset($data["UnpredictableNumber"])?$data["UnpredictableNumber"]:"";
            $this->ExtensionPoint = isset($data["ExtensionPoint"])?$data["ExtensionPoint"]:"";
        }
    }

    /**
     * Gets dsrp_data
     * @return string
     */
    public function getDsrpData()
    {
        return $this->DSRPData;
    }

    /**
     * Sets dsrp_data
     * @param string $dsrp_data the DSRP cryptogram generated by the consumers MasterPass wallet.
     * @return $this
     */
    public function setDsrpData($dsrp_data)
    {

        $this->DSRPData = $dsrp_data;
        return $this;
    }

    /**
     * Gets dsrp_data_type
     * @return string
     */
    public function getDsrpDataType()
    {
        return $this->DSRPDataType;
    }

    /**
     * Sets dsrp_data_type
     * @param string $dsrp_data_type the type of cryptogram generated by the consumers MasterPass wallet. MasterPass passes the most secure selection (ICC) if the merchant or service provider has indicated they can accept both types (UCAF, ICC).
     * @return $this
     */
    public function setDsrpDataType($dsrp_data_type)
    {

        $this->DSRPDataType = $dsrp_data_type;
        return $this;
    }

    /**
     * Gets unpredictable_number
     * @return string
     */
    public function getUnpredictableNumber()
    {
        return $this->UnpredictableNumber;
    }

    /**
     * Sets unpredictable_number
     * @param string $unpredictable_number the encoded EMV-quality random number generated by either the merchant or MasterPass.
     * @return $this
     */
    public function setUnpredictableNumber($unpredictable_number)
    {

        $this->UnpredictableNumber = $unpredictable_number;
        return $this;
    }

    /**
     * Gets extension_point
     * @return \mastercard_masterpass_merchant\model\ExtensionPoint
     */
    public function getExtensionPoint()
    {
        return $this->ExtensionPoint;
    }

    /**
     * Sets extension_point
     * @param \mastercard_masterpass_merchant\model\ExtensionPoint $extension_point the ExtensionPoint for future enhancement.
     * @return $this
     */
    public function setExtensionPoint($extension_point)
    {

        $this->ExtensionPoint = $extension_point;
        return $this;
    }




}

